### ISSUE TITLE
Voice constructor's velocity argument not used.

### ISSUE THREAD

**Issue by notator** [cwilso/midi-synth#18]
I've just incorporated this synth into my WebMIDISynthHost project [1], and see that the Voice constructor's velocity argument (js/synth.js, line 468) is not used. (It was used in an earlier version, but commented out, in line 478.)
How can it be used? Line 478 refers to a variable that no longer seems to exist...
Does this need fixing for both oscillators?

all the best,
James

[1] http://james-ingram-act-two.de/open-source/WebMIDISynthHost/host.html

**Comment by cwilso** [comment]
I just fixed up the comment, and added an osc2 one also, to show where to do it (see https://github.com/cwilso/midi-synth/commit/5d3dbae110e5b66fa4938b06163df470e2c115a4), but I didn't uncomment it, because I'd ideally like to have some controls over what the velocity argument does (applies to filter frequency, gain, attack only, etc.)

**Comment by notator** [comment]
Thanks. I'll update my copy accordingly.
Yes, I suppose there could be another control for deciding what the velocity does...
But whatever you do, MIDI is going to control the controls! ;-)
